Data extraction from url

In [2]:
pip install requests

Requirement already satisfied: requests in c:\users\anbalaghan\onedrive\desktop\streamlit\venv\lib\site-packages (2.32.5)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\anbalaghan\onedrive\desktop\streamlit\venv\lib\site-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\anbalaghan\onedrive\desktop\streamlit\venv\lib\site-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\anbalaghan\onedrive\desktop\streamlit\venv\lib\site-packages (from requests) (2.6.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\anbalaghan\onedrive\desktop\streamlit\venv\lib\site-packages (from requests) (2025.11.12)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
 # extracting data from url(usgs) and then  store it in one list

import requests
from datetime import date  # importing datetime

# getting earthquake data from usgs website

url = "https://earthquake.usgs.gov/fdsnws/event/1/query"
all_earthquakes = []  # list to store all earthquake records

# this is for get today's date
today = date.today()

# try to get the date exactly 5 years back
try:
    start_date_limit = today.replace(year=today.year - 5)  # 5 years back same day
except:
    # if problem with leap year (like feb 29)
    start_date_limit = date(today.year - 5, today.month, 28)

print("Collecting earthquakes from", start_date_limit, "to", today)      # for showing the total records till now

# loop for each year from start year to current year
for year in range(start_date_limit.year, today.year + 1):

    # loop for each month from 1 to 12 (n-1)
    for month in range(1, 13):

        # first day of this month
        month_start = date(year, month, 1)

        # find first day of next month
        if month == 12:
            month_end = date(year + 1, 1, 1)
        else:
            month_end = date(year, month + 1, 1)

        # skip if this month is fully before the start date
        if month_end <= start_date_limit:
            continue

        # skip if this month is after today (future)
        if month_start > today:
            continue

        # fix start date if it is before the allowed limit
        if month_start < start_date_limit:
            month_start = start_date_limit

        # fix end date if it goes beyond today
        if month_end > today:
            month_end = today

        print("Fetching:", month_start, "to", month_end)

        # parameters for the api request
        parameters = {
            "format": "geojson",
            "starttime": month_start.isoformat(),
            "endtime": month_end.isoformat(),
            "minmagnitude": 3
        }

        # make the api request (call)
        response = requests.get(url, params=parameters)

        # check if request is successful
        if response.status_code == 200:
            json_data = response.json()
            monthly_records = json_data.get("features", [])
            print("Events found:", len(monthly_records))

            # adding  all monthly records to main list
            all_earthquakes.extend(monthly_records)
        else:
            print("Request failed with status:", response.status_code)

# final count of all earthquake records
print("\nTotal earthquake records collected:", len(all_earthquakes))

Collecting earthquakes from 2020-12-13 to 2025-12-13
Fetching: 2020-12-13 to 2021-01-01
Events found: 966
Fetching: 2021-01-01 to 2021-02-01
Events found: 1713
Fetching: 2021-02-01 to 2021-03-01
Events found: 1812
Fetching: 2021-03-01 to 2021-04-01
Events found: 2433
Fetching: 2021-04-01 to 2021-05-01
Events found: 1577
Fetching: 2021-05-01 to 2021-06-01
Events found: 1602
Fetching: 2021-06-01 to 2021-07-01
Events found: 1612
Fetching: 2021-07-01 to 2021-08-01
Events found: 1799
Fetching: 2021-08-01 to 2021-09-01
Events found: 2683
Fetching: 2021-09-01 to 2021-10-01
Events found: 1688
Fetching: 2021-10-01 to 2021-11-01
Events found: 1536
Fetching: 2021-11-01 to 2021-12-01
Events found: 1542
Fetching: 2021-12-01 to 2022-01-01
Events found: 1914
Fetching: 2022-01-01 to 2022-02-01
Events found: 1910
Fetching: 2022-02-01 to 2022-03-01
Events found: 1615
Fetching: 2022-03-01 to 2022-04-01
Events found: 1917
Fetching: 2022-04-01 to 2022-05-01
Events found: 1657
Fetching: 2022-05-01 to 2022-06-01
Events found: 1507
Fetching: 2022-06-01 to 2022-07-01
Events found: 1530
Fetching: 2022-07-01 to 2022-08-01
Events found: 1693
Fetching: 2022-08-01 to 2022-09-01
Events found: 1681
Fetching: 2022-09-01 to 2022-10-01
Events found: 1903
Fetching: 2022-10-01 to 2022-11-01
Events found: 1618
Fetching: 2022-11-01 to 2022-12-01
Events found: 1644
Fetching: 2022-12-01 to 2023-01-01
Events found: 1533
Fetching: 2023-01-01 to 2023-02-01
Events found: 1787
Fetching: 2023-02-01 to 2023-03-01
Events found: 1852
Fetching: 2023-03-01 to 2023-04-01
Events found: 1634
Fetching: 2023-04-01 to 2023-05-01
Events found: 1548
Fetching: 2023-05-01 to 2023-06-01
Events found: 1851
Fetching: 2023-06-01 to 2023-07-01
Events found: 1644
Fetching: 2023-07-01 to 2023-08-01
Events found: 1559
Fetching: 2023-08-01 to 2023-09-01
Events found: 1499
Fetching: 2023-09-01 to 2023-10-01
Events found: 1453
Fetching: 2023-10-01 to 2023-11-01
Events found: 1738
Fetching: 2023-11-01 to 2023-12-01
Events found: 1752
Fetching: 2023-12-01 to 2024-01-01
Events found: 2514
Fetching: 2024-01-01 to 2024-02-01
Events found: 1734
Fetching: 2024-02-01 to 2024-03-01
Events found: 1529
Fetching: 2024-03-01 to 2024-04-01
Events found: 1446
Fetching: 2024-04-01 to 2024-05-01
Events found: 1841
Fetching: 2024-05-01 to 2024-06-01
Events found: 1608
Fetching: 2024-06-01 to 2024-07-01
Events found: 1435
Fetching: 2024-07-01 to 2024-08-01
Events found: 1444
Fetching: 2024-08-01 to 2024-09-01
Events found: 1426
Fetching: 2024-09-01 to 2024-10-01
Events found: 1386
Fetching: 2024-10-01 to 2024-11-01
Events found: 1525
Fetching: 2024-11-01 to 2024-12-01
Events found: 1437
Fetching: 2024-12-01 to 2025-01-01
Events found: 1848
Fetching: 2025-01-01 to 2025-02-01
Events found: 1745
Fetching: 2025-02-01 to 2025-03-01
Events found: 1712
Fetching: 2025-03-01 to 2025-04-01
Events found: 1634
Fetching: 2025-04-01 to 2025-05-01
Events found: 1688
Fetching: 2025-05-01 to 2025-06-01
Events found: 1586
Fetching: 2025-06-01 to 2025-07-01
Events found: 1499
Fetching: 2025-07-01 to 2025-08-01
Events found: 3328
Fetching: 2025-08-01 to 2025-09-01
Events found: 2569
Fetching: 2025-09-01 to 2025-10-01
Events found: 1886
Fetching: 2025-10-01 to 2025-11-01
Events found: 1677
Fetching: 2025-11-01 to 2025-12-01
Events found: 1348
Fetching: 2025-12-01 to 2025-12-13
Events found: 626

Total earthquake records collected: 103873

Data converting

In [4]:
pip install pandas

Requirement already satisfied: pandas in c:\users\anbalaghan\onedrive\desktop\streamlit\venv\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\anbalaghan\onedrive\desktop\streamlit\venv\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\anbalaghan\onedrive\desktop\streamlit\venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\anbalaghan\onedrive\desktop\streamlit\venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\anbalaghan\onedrive\desktop\streamlit\venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\anbalaghan\onedrive\desktop\streamlit\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
import pandas as pd                                                                  # converting list into a dataframe
df = pd.json_normalize(all_earthquakes)
print("DataFrame created with shape:", df.shape)                                     # gives  total count of rows and columns

DataFrame created with shape: (103873, 30)

In [6]:
df

,type,id,properties.mag,properties.place,properties.time,properties.updated,properties.tz,properties.url,properties.detail,properties.felt,...,properties.types,properties.nst,properties.dmin,properties.rms,properties.gap,properties.magType,properties.type,properties.title,geometry.type,geometry.coordinates
0,Feature,ak020gtokx7a,3.600000,"55 km S of Ivanof Bay, Alaska",1609457553709,1615072868040,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/fdsnws/event/1/que...,NaN,...,",origin,phase-data,shakemap,",NaN,NaN,0.61000,NaN,ml,earthquake,"M 3.6 - 55 km S of Ivanof Bay, Alaska",Point,"[-159.3768, 55.404, 7.1]"
1,Feature,us6000d4nn,4.800000,"74 km SSE of Bima, Indonesia",1609456355050,1615072868040,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/fdsnws/event/1/que...,1.0,...,",dyfi,origin,phase-data,",NaN,3.316000,0.90000,43.000000,mb,earthquake,"M 4.8 - 74 km SSE of Bima, Indonesia",Point,"[118.9156, -9.1109, 85.73]"
2,Feature,pr2020366008,3.340000,"46 km NNW of San Antonio, Puerto Rico",1609449480210,1615072867040,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/fdsnws/event/1/que...,NaN,...,",origin,phase-data,",15.0,0.444600,0.44000,224.000000,md,earthquake,"M 3.3 - 46 km NNW of San Antonio, Puerto Rico",Point,"[-67.219, 18.8988, 5]"
3,Feature,us6000d4mx,4.300000,"110 km WSW of Abra Pampa, Argentina",1609449194428,1615072866040,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/fdsnws/event/1/que...,NaN,...,",origin,phase-data,",NaN,1.322000,0.63000,112.000000,mb,earthquake,"M 4.3 - 110 km WSW of Abra Pampa, Argentina",Point,"[-66.7445, -22.9389, 284.27]"
4,Feature,us6000d4mj,4.000000,"18 km N of Stanton, Texas",1609447460034,1615072866040,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/fdsnws/event/1/que...,34.0,...,",dyfi,losspager,moment-tensor,origin,phase-dat...",NaN,0.316000,0.41000,35.000000,mwr,earthquake,"M 4.0 - 18 km N of Stanton, Texas",Point,"[-101.7941, 32.2951, 5]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103868,Feature,us7000ret9,4.100000,"47 km ESE of Aiquile, Bolivia",1764555755261,1764561845040,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/fdsnws/event/1/que...,NaN,...,",origin,phase-data,",12.0,0.686000,1.01000,121.000000,mb,earthquake,"M 4.1 - 47 km ESE of Aiquile, Bolivia",Point,"[-64.7474, -18.3206, 16.282]"
103869,Feature,ak2025xpgfse,3.008008,"59 km SSE of Halibut Cove, Alaska",1764553866060,1764554484040,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/fdsnws/event/1/que...,NaN,...,",origin,phase-data,",74.0,0.594635,0.72231,150.580002,ml,earthquake,"M 3.0 - 59 km SSE of Halibut Cove, Alaska",Point,"[-150.65530395507812, 59.1506233215332, 23.958..."
103870,Feature,us7000ret3,4.600000,"60 km E of Baculin, Philippines",1764553304083,1764554196040,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/fdsnws/event/1/que...,NaN,...,",origin,phase-data,",37.0,1.556000,1.20000,102.000000,mb,earthquake,"M 4.6 - 60 km E of Baculin, Philippines",Point,"[127.1211, 7.3542, 32.106]"
103871,Feature,us7000ret2,4.100000,"78 km SW of Challapata, Bolivia",1764553077834,1764553748040,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/fdsnws/event/1/que...,NaN,...,",origin,phase-data,",14.0,2.371000,0.74000,95.000000,mb,earthquake,"M 4.1 - 78 km SW of Challapata, Bolivia",Point,"[-67.2764, -19.4176, 227.844]"
103872,Feature,us7000resx,4.600000,"20 km W of Urakawa, Japan",1764550080828,1764566544040,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/fdsnws/event/1/que...,NaN,...,",origin,phase-data,",38.0,0.472000,0.47000,76.000000,mb,earthquake,"M 4.6 - 20 km W of Urakawa, Japan",Point,"[142.5397, 42.1226, 46.556]"

Data cleaning and Handling

Name changing

In [7]:
df.columns=['Type', 'id', 'mag', 'place', 'time',                                     # changing column names 
       'updated', 'tz', 'url',
       'detail', 'felt', 'cdi',
       'mmi', 'alert', 'status',
       'tsunami', 'sig', 'net',
       'code', 'ids', 'sources',
       'types', 'nst', 'dmin',
       'rms', 'gap', 'magType',
       'e_type', 'title', 'gtype',
       'coordinates']

In [8]:
df.columns

Index(['Type', 'id', 'mag', 'place', 'time', 'updated', 'tz', 'url', 'detail',
       'felt', 'cdi', 'mmi', 'alert', 'status', 'tsunami', 'sig', 'net',
       'code', 'ids', 'sources', 'types', 'nst', 'dmin', 'rms', 'gap',
       'magType', 'e_type', 'title', 'gtype', 'coordinates'],
      dtype='object')

deriving new columns

In [9]:
df["time"] = pd.to_datetime(df["time"], unit='ms')        
df["updated"] = pd.to_datetime(df["updated"], unit='ms')                              # converting time from milliseconds to datetime

In [10]:
df[['time','updated']]

                          time                 updated
0      2020-12-31 23:32:33.709 2021-03-06 23:21:08.040
1      2020-12-31 23:12:35.050 2021-03-06 23:21:08.040
2      2020-12-31 21:18:00.210 2021-03-06 23:21:07.040
3      2020-12-31 21:13:14.428 2021-03-06 23:21:06.040
4      2020-12-31 20:44:20.034 2021-03-06 23:21:06.040
...                        ...                     ...
103868 2025-12-01 02:22:35.261 2025-12-01 04:04:05.040
103869 2025-12-01 01:51:06.060 2025-12-01 02:01:24.040
103870 2025-12-01 01:41:44.083 2025-12-01 01:56:36.040
103871 2025-12-01 01:37:57.834 2025-12-01 01:49:08.040
103872 2025-12-01 00:48:00.828 2025-12-01 05:22:24.040

[103873 rows x 2 columns]

In [11]:
df["longitude"] = df["coordinates"].apply(lambda x: x[0])
df["latitude"]  = df["coordinates"].apply(lambda x: x[1])                             # extracting values and deriving new columns 
df["depth_km"]  = df["coordinates"].apply(lambda x: x[2])

In [12]:
df[["longitude","latitude","depth_km"]]

         longitude   latitude    depth_km
0      -159.376800  55.404000    7.100000
1       118.915600  -9.110900   85.730000
2       -67.219000  18.898800    5.000000
3       -66.744500 -22.938900  284.270000
4      -101.794100  32.295100    5.000000
...            ...        ...         ...
103868  -64.747400 -18.320600   16.282000
103869 -150.655304  59.150623   23.958218
103870  127.121100   7.354200   32.106000
103871  -67.276400 -19.417600  227.844000
103872  142.539700  42.122600   46.556000

[103873 rows x 3 columns]

In [13]:
# to seperate country name
df['country'] = df['place'].str.split(',').str[-1].str.strip()

In [14]:
df["country"]

0              Alaska
1           Indonesia
2         Puerto Rico
3           Argentina
4               Texas
             ...
103868        Bolivia
103869         Alaska
103870    Philippines
103871        Bolivia
103872          Japan
Name: country, Length: 103873, dtype: object

In [15]:
df['year'] = df['time'].dt.year                                                       # separating year from time

In [16]:
df['month'] = df['time'].dt.month                                                     # separating month from time

In [17]:
df['day'] = df['time'].dt.day                                                         # separating day from time

In [18]:
df['day_of_week'] = df['time'].dt.day_name()                                          # separating day_of_week from time

In [19]:
df[['day_of_week','year','month','day']]

       day_of_week  year  month  day
0         Thursday  2020     12   31
1         Thursday  2020     12   31
2         Thursday  2020     12   31
3         Thursday  2020     12   31
4         Thursday  2020     12   31
...            ...   ...    ...  ...
103868      Monday  2025     12    1
103869      Monday  2025     12    1
103870      Monday  2025     12    1
103871      Monday  2025     12    1
103872      Monday  2025     12    1

[103873 rows x 4 columns]

In [20]:
df['depth_flag'] = df['depth_km'].apply(lambda x: 'shallow' if x <= 70 else 'deep')   # creating Shallow/deep earthquake flag column based on depth_km.

In [21]:
df['mag_flag'] = df['mag'].apply(lambda x: 'destructive' if x >=6 else 'strong')      # creating Strong/destructive flag columns based on mag thresholds.

In [22]:
df[['mag_flag','depth_flag']]

       mag_flag depth_flag
0        strong    shallow
1        strong       deep
2        strong    shallow
3        strong       deep
4        strong    shallow
...         ...        ...
103868   strong    shallow
103869   strong    shallow
103870   strong    shallow
103871   strong       deep
103872   strong    shallow

[103873 rows x 2 columns]

In [23]:
df.columns

Index(['Type', 'id', 'mag', 'place', 'time', 'updated', 'tz', 'url', 'detail',
       'felt', 'cdi', 'mmi', 'alert', 'status', 'tsunami', 'sig', 'net',
       'code', 'ids', 'sources', 'types', 'nst', 'dmin', 'rms', 'gap',
       'magType', 'e_type', 'title', 'gtype', 'coordinates', 'longitude',
       'latitude', 'depth_km', 'country', 'year', 'month', 'day',
       'day_of_week', 'depth_flag', 'mag_flag'],
      dtype='object')

Data correction

In [24]:
df['felt'] = df['felt'].fillna(0)                      #Filling missing numeric values with 0

In [25]:
df['cdi'] = df['cdi'].fillna(0)                        #Fill missing numeric values with 0

In [26]:
df['mmi'] = df['mmi'].fillna(0)                        #Fill missing numeric values with 0

In [27]:
df[["felt","cdi","mmi"]].isna().sum()

felt    0
cdi     0
mmi     0
dtype: int64

In [28]:
df['dmin'] = df['dmin'].fillna(df['dmin'].mean())      #replacing NaN values with mean values

In [29]:
df['nst'] = df['nst'].fillna(df['nst'].mean())         #replacing NaN values with mean values

In [30]:
df['gap'] = df['gap'].fillna(df['gap'].mean())         #replacing NaN values with mean values

In [31]:
df['rms'] = df['rms'].fillna(df['rms'].mean())         #replacing NaN values with mean values

In [32]:
df[["dmin","nst","gap","rms"]].isna().sum()

dmin    0
nst     0
gap     0
rms     0
dtype: int64

In [33]:
df.drop(["Type","tz","url","detail","coordinates","title","gtype"],axis=1,inplace=True) #  dropping columns

In [34]:
arranged_column = ["id","time","updated","year","month","day","day_of_week","mag","mag_flag","magType","depth_km","depth_flag","longitude","latitude","place","country","e_type","tsunami","sources","net","alert","felt","cdi","mmi","types","sig","code","ids","nst","dmin","rms","gap","status"]
df = df[arranged_column]                               # arranging columns for better understanding

In [35]:
df.columns

Index(['id', 'time', 'updated', 'year', 'month', 'day', 'day_of_week', 'mag',
       'mag_flag', 'magType', 'depth_km', 'depth_flag', 'longitude',
       'latitude', 'place', 'country', 'e_type', 'tsunami', 'sources', 'net',
       'alert', 'felt', 'cdi', 'mmi', 'types', 'sig', 'code', 'ids', 'nst',
       'dmin', 'rms', 'gap', 'status'],
      dtype='object')

In [36]:
pip install sqlalchemy pymysql

Requirement already satisfied: sqlalchemy in c:\users\anbalaghan\onedrive\desktop\streamlit\venv\lib\site-packages (2.0.45)
Requirement already satisfied: pymysql in c:\users\anbalaghan\onedrive\desktop\streamlit\venv\lib\site-packages (1.1.2)
Requirement already satisfied: greenlet>=1 in c:\users\anbalaghan\onedrive\desktop\streamlit\venv\lib\site-packages (from sqlalchemy) (3.3.0)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\anbalaghan\onedrive\desktop\streamlit\venv\lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
import pandas as pd
from sqlalchemy import create_engine

# Creating connection to MySQL
engine = create_engine("mysql+pymysql://root:root@localhost/guvi_project_1")


df_cleaned = df 

#  Inserting into MySQL
df_cleaned.to_sql(
    name='earthquakes',
    con=engine,
    if_exists='replace',
    index=False
)

print("Data inserted successfully!")

Data inserted successfully!